services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ~/minio/data:/data
    environment:
      - "MINIO_ROOT_USER=accesskey"
      - "MINIO_ROOT_PASSWORD=secretkey"
    command: server /data --console-address ":9090"
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 accesskey secretkey;
      /usr/bin/mc rm -r --force myminio/project;
      /usr/bin/mc mb myminio/project;
      /usr/bin/mc policy download myminio/project;
      exit 0;
      "   